name: Build and deploy ASP.Net Core app to Azure Web App - DevPortfolio20240614070249

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0"
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release server/DevPortfolio

      - name: dotnet publish
        run: dotnet publish --configuration Release --output ${{env.DOTNET_ROOT}}/myapp server/DevPortfolio

      - name: List published files
        run: dir ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: List Downloaded files
        run: dir ${{ github.workspace }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B725EE52B9D545C48329363BBB34A692 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_58451DDBF6A742368FA69315D48D3D91 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4BEEC8975E9C4201BDDB893D0B1EADC5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "DevPortfolio20240614070249"
          slot-name: "Production"
          package: ${{ github.workspace }}
